// cohn.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Fri Oct  4 17:02:52 UTC 2024

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf messages for Camera On the Home Network

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.6.1
// source: cohn.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumCOHNStatus int32

const (
	EnumCOHNStatus_COHN_UNPROVISIONED EnumCOHNStatus = 0
	EnumCOHNStatus_COHN_PROVISIONED   EnumCOHNStatus = 1
)

// Enum value maps for EnumCOHNStatus.
var (
	EnumCOHNStatus_name = map[int32]string{
		0: "COHN_UNPROVISIONED",
		1: "COHN_PROVISIONED",
	}
	EnumCOHNStatus_value = map[string]int32{
		"COHN_UNPROVISIONED": 0,
		"COHN_PROVISIONED":   1,
	}
)

func (x EnumCOHNStatus) Enum() *EnumCOHNStatus {
	p := new(EnumCOHNStatus)
	*p = x
	return p
}

func (x EnumCOHNStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumCOHNStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cohn_proto_enumTypes[0].Descriptor()
}

func (EnumCOHNStatus) Type() protoreflect.EnumType {
	return &file_cohn_proto_enumTypes[0]
}

func (x EnumCOHNStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumCOHNStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumCOHNStatus(num)
	return nil
}

// Deprecated: Use EnumCOHNStatus.Descriptor instead.
func (EnumCOHNStatus) EnumDescriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{0}
}

type EnumCOHNNetworkState int32

const (
	EnumCOHNNetworkState_COHN_STATE_Init                EnumCOHNNetworkState = 0
	EnumCOHNNetworkState_COHN_STATE_Error               EnumCOHNNetworkState = 1
	EnumCOHNNetworkState_COHN_STATE_Exit                EnumCOHNNetworkState = 2
	EnumCOHNNetworkState_COHN_STATE_Idle                EnumCOHNNetworkState = 5
	EnumCOHNNetworkState_COHN_STATE_NetworkConnected    EnumCOHNNetworkState = 27
	EnumCOHNNetworkState_COHN_STATE_NetworkDisconnected EnumCOHNNetworkState = 28
	EnumCOHNNetworkState_COHN_STATE_ConnectingToNetwork EnumCOHNNetworkState = 29
	EnumCOHNNetworkState_COHN_STATE_Invalid             EnumCOHNNetworkState = 30
)

// Enum value maps for EnumCOHNNetworkState.
var (
	EnumCOHNNetworkState_name = map[int32]string{
		0:  "COHN_STATE_Init",
		1:  "COHN_STATE_Error",
		2:  "COHN_STATE_Exit",
		5:  "COHN_STATE_Idle",
		27: "COHN_STATE_NetworkConnected",
		28: "COHN_STATE_NetworkDisconnected",
		29: "COHN_STATE_ConnectingToNetwork",
		30: "COHN_STATE_Invalid",
	}
	EnumCOHNNetworkState_value = map[string]int32{
		"COHN_STATE_Init":                0,
		"COHN_STATE_Error":               1,
		"COHN_STATE_Exit":                2,
		"COHN_STATE_Idle":                5,
		"COHN_STATE_NetworkConnected":    27,
		"COHN_STATE_NetworkDisconnected": 28,
		"COHN_STATE_ConnectingToNetwork": 29,
		"COHN_STATE_Invalid":             30,
	}
)

func (x EnumCOHNNetworkState) Enum() *EnumCOHNNetworkState {
	p := new(EnumCOHNNetworkState)
	*p = x
	return p
}

func (x EnumCOHNNetworkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumCOHNNetworkState) Descriptor() protoreflect.EnumDescriptor {
	return file_cohn_proto_enumTypes[1].Descriptor()
}

func (EnumCOHNNetworkState) Type() protoreflect.EnumType {
	return &file_cohn_proto_enumTypes[1]
}

func (x EnumCOHNNetworkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumCOHNNetworkState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumCOHNNetworkState(num)
	return nil
}

// Deprecated: Use EnumCOHNNetworkState.Descriptor instead.
func (EnumCOHNNetworkState) EnumDescriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{1}
}

// *
// Get the current COHN status.
//
// Response: @ref NotifyCOHNStatus
//
// Additionally, asynchronous updates can also be registered to return more @ref NotifyCOHNStatus when a value
// changes.
type RequestGetCOHNStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisterCohnStatus *bool `protobuf:"varint,1,opt,name=register_cohn_status,json=registerCohnStatus" json:"register_cohn_status,omitempty"` // 1 to register, 0 to unregister
}

func (x *RequestGetCOHNStatus) Reset() {
	*x = RequestGetCOHNStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetCOHNStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetCOHNStatus) ProtoMessage() {}

func (x *RequestGetCOHNStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetCOHNStatus.ProtoReflect.Descriptor instead.
func (*RequestGetCOHNStatus) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetCOHNStatus) GetRegisterCohnStatus() bool {
	if x != nil && x.RegisterCohnStatus != nil {
		return *x.RegisterCohnStatus
	}
	return false
}

// Current COHN status triggered by a @ref RequestGetCOHNStatus
type NotifyCOHNStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     *EnumCOHNStatus       `protobuf:"varint,1,opt,name=status,enum=open_gopro.EnumCOHNStatus" json:"status,omitempty"`     // Current COHN status
	State      *EnumCOHNNetworkState `protobuf:"varint,2,opt,name=state,enum=open_gopro.EnumCOHNNetworkState" json:"state,omitempty"` // Current COHN network state
	Username   *string               `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`                                 // Username used for http basic auth header
	Password   *string               `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`                                 // Password used for http basic auth header
	Ipaddress  *string               `protobuf:"bytes,5,opt,name=ipaddress" json:"ipaddress,omitempty"`                               // Camera's IP address on the local network
	Enabled    *bool                 `protobuf:"varint,6,opt,name=enabled" json:"enabled,omitempty"`                                  // Is COHN currently enabled?
	Ssid       *string               `protobuf:"bytes,7,opt,name=ssid" json:"ssid,omitempty"`                                         // Currently connected SSID
	Macaddress *string               `protobuf:"bytes,8,opt,name=macaddress" json:"macaddress,omitempty"`                             // MAC address of the wifi adapter
}

func (x *NotifyCOHNStatus) Reset() {
	*x = NotifyCOHNStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyCOHNStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyCOHNStatus) ProtoMessage() {}

func (x *NotifyCOHNStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyCOHNStatus.ProtoReflect.Descriptor instead.
func (*NotifyCOHNStatus) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyCOHNStatus) GetStatus() EnumCOHNStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return EnumCOHNStatus_COHN_UNPROVISIONED
}

func (x *NotifyCOHNStatus) GetState() EnumCOHNNetworkState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return EnumCOHNNetworkState_COHN_STATE_Init
}

func (x *NotifyCOHNStatus) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *NotifyCOHNStatus) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *NotifyCOHNStatus) GetIpaddress() string {
	if x != nil && x.Ipaddress != nil {
		return *x.Ipaddress
	}
	return ""
}

func (x *NotifyCOHNStatus) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *NotifyCOHNStatus) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *NotifyCOHNStatus) GetMacaddress() string {
	if x != nil && x.Macaddress != nil {
		return *x.Macaddress
	}
	return ""
}

// *
// Create the Camera On the Home Network SSL/TLS certificate.
//
// Returns a @ref ResponseGeneric with the status of the creation
type RequestCreateCOHNCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Override *bool `protobuf:"varint,1,opt,name=override" json:"override,omitempty"` // Override current provisioning and create new cert
}

func (x *RequestCreateCOHNCert) Reset() {
	*x = RequestCreateCOHNCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreateCOHNCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateCOHNCert) ProtoMessage() {}

func (x *RequestCreateCOHNCert) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateCOHNCert.ProtoReflect.Descriptor instead.
func (*RequestCreateCOHNCert) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCreateCOHNCert) GetOverride() bool {
	if x != nil && x.Override != nil {
		return *x.Override
	}
	return false
}

// *
// Clear the COHN certificate.
//
// Returns a @ref ResponseGeneric with the status of the clear
type RequestClearCOHNCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestClearCOHNCert) Reset() {
	*x = RequestClearCOHNCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestClearCOHNCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestClearCOHNCert) ProtoMessage() {}

func (x *RequestClearCOHNCert) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestClearCOHNCert.ProtoReflect.Descriptor instead.
func (*RequestClearCOHNCert) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{3}
}

// *
// Get the COHN certificate.
//
// Returns a @ref ResponseCOHNCert
type RequestCOHNCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestCOHNCert) Reset() {
	*x = RequestCOHNCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCOHNCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCOHNCert) ProtoMessage() {}

func (x *RequestCOHNCert) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCOHNCert.ProtoReflect.Descriptor instead.
func (*RequestCOHNCert) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{4}
}

// COHN Certificate response triggered by @ref RequestCOHNCert
type ResponseCOHNCert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *EnumResultGeneric `protobuf:"varint,1,opt,name=result,enum=open_gopro.EnumResultGeneric" json:"result,omitempty"` // Was request successful?
	Cert   *string            `protobuf:"bytes,2,opt,name=cert" json:"cert,omitempty"`                                        // Root CA cert (ASCII text)
}

func (x *ResponseCOHNCert) Reset() {
	*x = ResponseCOHNCert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCOHNCert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCOHNCert) ProtoMessage() {}

func (x *ResponseCOHNCert) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCOHNCert.ProtoReflect.Descriptor instead.
func (*ResponseCOHNCert) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseCOHNCert) GetResult() EnumResultGeneric {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return EnumResultGeneric_RESULT_UNKNOWN
}

func (x *ResponseCOHNCert) GetCert() string {
	if x != nil && x.Cert != nil {
		return *x.Cert
	}
	return ""
}

// *
// Configure a COHN Setting
//
// Returns a @ref ResponseGeneric
type RequestSetCOHNSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// 1 to enable COHN, 0 to disable COHN
	//
	// When set to 1, STA Mode connection will be dropped and camera will not automatically re-connect for COHN.
	CohnActive *bool `protobuf:"varint,1,opt,name=cohn_active,json=cohnActive" json:"cohn_active,omitempty"`
}

func (x *RequestSetCOHNSetting) Reset() {
	*x = RequestSetCOHNSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cohn_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSetCOHNSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSetCOHNSetting) ProtoMessage() {}

func (x *RequestSetCOHNSetting) ProtoReflect() protoreflect.Message {
	mi := &file_cohn_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSetCOHNSetting.ProtoReflect.Descriptor instead.
func (*RequestSetCOHNSetting) Descriptor() ([]byte, []int) {
	return file_cohn_proto_rawDescGZIP(), []int{6}
}

func (x *RequestSetCOHNSetting) GetCohnActive() bool {
	if x != nil && x.CohnActive != nil {
		return *x.CohnActive
	}
	return false
}

var File_cohn_proto protoreflect.FileDescriptor

var file_cohn_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6f, 0x68, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x70,
	0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x1a, 0x16, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x48, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x43, 0x4f,
	0x48, 0x4e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x68, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x43, 0x6f, 0x68, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xa2, 0x02, 0x0a, 0x10, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x4f, 0x48, 0x4e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x43, 0x4f, 0x48, 0x4e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x43, 0x4f, 0x48, 0x4e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x73, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x73, 0x69, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x63, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x63, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x33, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x4f, 0x48, 0x4e, 0x43, 0x65, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x43, 0x4f, 0x48, 0x4e, 0x43, 0x65, 0x72, 0x74, 0x22, 0x11, 0x0a, 0x0f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x4f, 0x48, 0x4e, 0x43, 0x65, 0x72, 0x74, 0x22,
	0x5d, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x4f, 0x48, 0x4e, 0x43,
	0x65, 0x72, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
	0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0x38,
	0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74, 0x43, 0x4f, 0x48, 0x4e,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x68, 0x6e, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f,
	0x68, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2a, 0x3e, 0x0a, 0x0e, 0x45, 0x6e, 0x75, 0x6d,
	0x43, 0x4f, 0x48, 0x4e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4f,
	0x48, 0x4e, 0x5f, 0x55, 0x4e, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x53, 0x49, 0x4f, 0x4e, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x53, 0x49, 0x4f, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x2a, 0xec, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x75,
	0x6d, 0x43, 0x4f, 0x48, 0x4e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x49, 0x6e, 0x69, 0x74, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x78, 0x69, 0x74, 0x10,
	0x02, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x49, 0x64, 0x6c, 0x65, 0x10, 0x05, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x1b, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4f, 0x48, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x1c, 0x12, 0x22, 0x0a, 0x1e, 0x43,
	0x4f, 0x48, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x10, 0x1d, 0x12,
	0x16, 0x0a, 0x12, 0x43, 0x4f, 0x48, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x1e, 0x42, 0x03, 0x5a, 0x01, 0x2e,
}

var (
	file_cohn_proto_rawDescOnce sync.Once
	file_cohn_proto_rawDescData = file_cohn_proto_rawDesc
)

func file_cohn_proto_rawDescGZIP() []byte {
	file_cohn_proto_rawDescOnce.Do(func() {
		file_cohn_proto_rawDescData = protoimpl.X.CompressGZIP(file_cohn_proto_rawDescData)
	})
	return file_cohn_proto_rawDescData
}

var file_cohn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cohn_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cohn_proto_goTypes = []interface{}{
	(EnumCOHNStatus)(0),           // 0: open_gopro.EnumCOHNStatus
	(EnumCOHNNetworkState)(0),     // 1: open_gopro.EnumCOHNNetworkState
	(*RequestGetCOHNStatus)(nil),  // 2: open_gopro.RequestGetCOHNStatus
	(*NotifyCOHNStatus)(nil),      // 3: open_gopro.NotifyCOHNStatus
	(*RequestCreateCOHNCert)(nil), // 4: open_gopro.RequestCreateCOHNCert
	(*RequestClearCOHNCert)(nil),  // 5: open_gopro.RequestClearCOHNCert
	(*RequestCOHNCert)(nil),       // 6: open_gopro.RequestCOHNCert
	(*ResponseCOHNCert)(nil),      // 7: open_gopro.ResponseCOHNCert
	(*RequestSetCOHNSetting)(nil), // 8: open_gopro.RequestSetCOHNSetting
	(EnumResultGeneric)(0),        // 9: open_gopro.EnumResultGeneric
}
var file_cohn_proto_depIdxs = []int32{
	0, // 0: open_gopro.NotifyCOHNStatus.status:type_name -> open_gopro.EnumCOHNStatus
	1, // 1: open_gopro.NotifyCOHNStatus.state:type_name -> open_gopro.EnumCOHNNetworkState
	9, // 2: open_gopro.ResponseCOHNCert.result:type_name -> open_gopro.EnumResultGeneric
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cohn_proto_init() }
func file_cohn_proto_init() {
	if File_cohn_proto != nil {
		return
	}
	file_response_generic_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cohn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetCOHNStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cohn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyCOHNStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cohn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreateCOHNCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cohn_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestClearCOHNCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cohn_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCOHNCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cohn_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCOHNCert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cohn_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSetCOHNSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cohn_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cohn_proto_goTypes,
		DependencyIndexes: file_cohn_proto_depIdxs,
		EnumInfos:         file_cohn_proto_enumTypes,
		MessageInfos:      file_cohn_proto_msgTypes,
	}.Build()
	File_cohn_proto = out.File
	file_cohn_proto_rawDesc = nil
	file_cohn_proto_goTypes = nil
	file_cohn_proto_depIdxs = nil
}
